### ISSUE TITLE
getuser() invoked by utilities.py fails in container

### ISSUE THREAD

**Issue by rptaylor** [PanDAWMS/pilot2#330]
Hi @PalNilsson 

Just like #327 , there is another spot that invokes the problematic function, this time it is happening in utilities.py.

We are using the latest pilot version on CVMFS.
```
---- Retrieve pilot code ----
2021-01-23 00:13:11,137 [wrapper] Using piloturl: file:///cvmfs/atlas.cern.ch/repo/sw/PandaPilot/tar/pilot2.tar.gz
2021-01-23 00:13:11,166 [wrapper] File pilot2/pilot.py exists OK
2021-01-23 00:13:11,170 [wrapper] pilot2/PILOTVERSION: 2.9.4.20



---- Ready to run pilot ----

2021-01-23 00:13:21,136 [wrapper] ==== pilot stdout BEGIN ====
2021-01-23 00:13:21,139 [wrapper] pilotpid: 3371
2021-01-23 00:13:21,349 | INFO     | MainThread          | pilot.util.auxiliary             | pilot_version_banner      | ****************************************
2021-01-23 00:13:21,349 | INFO     | MainThread          | pilot.util.auxiliary             | pilot_version_banner      | ***  PanDA Pilot version 2.9.4 (20)  ***
2021-01-23 00:13:21,350 | INFO     | MainThread          | pilot.util.auxiliary             | pilot_version_banner      | ****************************************
2021-01-23 00:13:21,350 | INFO     | MainThread          | pilot.util.auxiliary             | pilot_version_banner      | 
2021-01-23 00:13:21,350 | INFO     | MainThread          | pilot.util.auxiliary             | pilot_version_banner      | pilot is running in a VM
2021-01-23 00:13:21,350 | INFO     | MainThread          | pilot.util.auxiliary             | display_architecture_info | architecture information:
2021-01-23 00:13:21,424 | INFO     | MainThread          | pilot.util.auxiliary             | display_architecture_info | 



2021-01-23 00:13:24,632 | INFO     | validate            | pilot.control.job                | validate                  | processing PanDA job 4955393196 from task NULL
  File "/pilotdir/atlas_t5eX0Gry/pilot2/pilot/common/exception.py", line 434, in run
    self._Thread__target(**self._Thread__kwargs)
  File "/pilotdir/atlas_t5eX0Gry/pilot2/pilot/control/job.py", line 770, in validate
    if _validate_job(job):
  File "/pilotdir/atlas_t5eX0Gry/pilot2/pilot/control/job.py", line 135, in _validate_job
    user = __import__('pilot.user.%s.common' % pilot_user, globals(), locals(), [pilot_user], 0)  # Python 2/3
  File "/pilotdir/atlas_t5eX0Gry/pilot2/pilot/user/atlas/common.py", line 27, in <module>
    from .utilities import get_memory_monitor_setup, get_network_monitor_setup, post_memory_monitor_action,\
  File "/pilotdir/atlas_t5eX0Gry/pilot2/pilot/user/atlas/utilities.py", line 257, in <module>
    def get_ps_info(pgrp, whoami=getuser(), options='axfo pid,user,args'):
  File "/usr/lib64/python2.7/getpass.py", line 158, in getuser
    return pwd.getpwuid(os.getuid())[0]
exception caught by thread run() function: (<type 'exceptions.KeyError'>, KeyError('getpwuid(): uid not found: 1000',), <traceback object at 0x7f99c4426290>)
Traceback (most recent call last):
  File "/pilotdir/atlas_t5eX0Gry/pilot2/pilot/common/exception.py", line 434, in run
    self._Thread__target(**self._Thread__kwargs)
  File "/pilotdir/atlas_t5eX0Gry/pilot2/pilot/control/job.py", line 770, in validate
    if _validate_job(job):
  File "/pilotdir/atlas_t5eX0Gry/pilot2/pilot/control/job.py", line 135, in _validate_job
    user = __import__('pilot.user.%s.common' % pilot_user, globals(), locals(), [pilot_user], 0)  # Python 2/3
  File "/pilotdir/atlas_t5eX0Gry/pilot2/pilot/user/atlas/common.py", line 27, in <module>
    from .utilities import get_memory_monitor_setup, get_network_monitor_setup, post_memory_monitor_action,\
  File "/pilotdir/atlas_t5eX0Gry/pilot2/pilot/user/atlas/utilities.py", line 257, in <module>
    def get_ps_info(pgrp, whoami=getuser(), options='axfo pid,user,args'):
  File "/usr/lib64/python2.7/getpass.py", line 158, in getuser
    return pwd.getpwuid(os.getuid())[0]
KeyError: 'getpwuid(): uid not found: 1000'
```

I grepped for getuser in the pilot code, this should be the only remaining case that causes the problem.

Thanks!

**Comment by rptaylor** [comment]
heads up to @fbarreir  , this will fix the remaining issue on the dev cluster.

**Comment by PalNilsson** [comment]
Hi @rptaylor, I've fixed it in the dev pilot. I will update the stable PRE release version later today. You can use it in the meantime until the next release, if it's urgent. I can send you the link to it separately. Cheers

**Comment by rptaylor** [comment]
Thanks @PalNilsson , do you have an estimate of when the updated version with the fix will be in the prod pilot on CVMFS?

**Comment by PalNilsson** [comment]
I'm aiming for Wednesday-Thursday this week. But you can use the PRE version before then (perhaps the final version). Just set the PQ.pilot_url to 'http://cern.ch/atlas-panda-pilot/pilot2-PRE.tar.gz'.
