### ISSUE TITLE
Starting pilot2

### ISSUE THREAD

**Issue by pavlo-svirin** [PanDAWMS/pilot2#4]
Hi all! Got trouble starting pilot2:

$ ./pilot.py --cacert /tmp/x509up_u500 -d -q BNL-LSST
2017-04-19 21:59:13,490 | INFO     | MainThread | __main__                         | main                             | pilot startup - version 2017-04-04.001
2017-04-19 21:59:13,513 | DEBUG    | MainThread | pilot.util.https                 | https_setup                      | User-Agent: pilot/2017-04-04.001 (Python 2.6.6; Linux x86_64)
2017-04-19 21:59:13,516 | WARNING  | MainThread | pilot.util.https                 | https_setup                      | Python version <2.7.9 lacks SSL contexts -- falling back to curl
2017-04-19 21:59:13,525 | DEBUG    | MainThread | pilot.util.information           | retrieve_json                    | retrieving: http://atlas-agis-api.cern.ch/request/pandaqueue/query/list/?json
2017-04-19 21:59:18,706 | DEBUG    | MainThread | pilot.util.information           | retrieve_json                    | cached version found: http://atlas-agis-api.cern.ch/request/pandaqueue/query/list/?json
2017-04-19 21:59:18,717 | DEBUG    | MainThread | pilot.util.information           | retrieve_json                    | retrieving: http://atlas-agis-api.cern.ch/request/site/query/list/?json
2017-04-19 21:59:21,256 | DEBUG    | MainThread | pilot.util.information           | retrieve_json                    | cached version found: http://atlas-agis-api.cern.ch/request/site/query/list/?json
Traceback (most recent call last):
  File "./pilot.py", line 104, in <module>
    trace = main()
  File "./pilot.py", line 31, in main
    if not set_location(args):
  File "/home/hellcat/dev/pilot2/pilot/util/information.py", line 56, in set_location
    args.location.site_info = [tmp_site for tmp_site in all_sites if site['name'] == args.location.site][0]
TypeError: 'NoneType' object is unsubscriptable

$ voms-proxy-info
subject   : /DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=psvirin/CN=762973/CN=Pavlo Svirin/CN=proxy
issuer    : /DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=psvirin/CN=762973/CN=Pavlo Svirin
identity  : /DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=psvirin/CN=762973/CN=Pavlo Svirin
type      : proxy
strength  : 1024 bits
path      : /tmp/x509up_u500
timeleft  : 11:30:25

$ git status
# On branch next
nothing to commit (working directory clean)

**Comment by complynx** [comment]
Tried to fix the issue, fixed array names, but there is more issues
https://github.com/complynx/pilot2/tree/fix-issue-4


[ddrizhuk@lxplus048 pilot2]$ git checkout fix-issue-4 --force
Branch fix-issue-4 set up to track remote branch fix-issue-4 from origin.
Switched to a new branch 'fix-issue-4'
[ddrizhuk@lxplus048 pilot2]$ ./pilot.py -d -q BNL-LSST
2017-04-19 23:05:15,880 | INFO     | MainThread | __main__                         | main                             | pilot startup - version 2017-04-04.001
2017-04-19 23:05:15,946 | DEBUG    | MainThread | pilot.util.https                 | https_setup                      | User-Agent: pilot/2017-04-04.001 (Python 2.6.6; Linux x86_64)
2017-04-19 23:05:15,946 | WARNING  | MainThread | pilot.util.https                 | https_setup                      | Python version <2.7.9 lacks SSL contexts -- falling back to curl
2017-04-19 23:05:15,948 | DEBUG    | MainThread | pilot.util.information           | retrieve_json                    | retrieving: http://atlas-agis-api.cern.ch/request/pandaqueue/query/list/?json
2017-04-19 23:05:16,667 | DEBUG    | MainThread | pilot.util.information           | retrieve_json                    | cached version found: http://atlas-agis-api.cern.ch/request/pandaqueue/query/list/?json
2017-04-19 23:05:16,669 | DEBUG    | MainThread | pilot.util.information           | retrieve_json                    | retrieving: http://atlas-agis-api.cern.ch/request/site/query/list/?json
2017-04-19 23:05:17,033 | DEBUG    | MainThread | pilot.util.information           | retrieve_json                    | cached version found: http://atlas-agis-api.cern.ch/request/site/query/list/?json
Traceback (most recent call last):
  File "./pilot.py", line 104, in <module>
    trace = main()
  File "./pilot.py", line 31, in main
    if not set_location(args):
  File "/afs/cern.ch/user/d/ddrizhuk/pilot2/pilot/util/information.py", line 55, in set_location
    args.location.site = str(matching_sites[0]['site'])
KeyError: 'site'

**Comment by complynx** [comment]
Wrong guess

**Comment by complynx** [comment]
see branch https://github.com/complynx/pilot2/tree/fix-issue-4

**Comment by pavlo-svirin** [comment]
Thank you, much better! Will it be merged into main repo?

Now the only warning I get is:

request: curl -sS --compressed --connect-timeout 1 --max-time 3 --capath /etc/grid-security/certificates --cert /tmp/x509up_u500 --cacert /tmp/x509up_u500 --key /tmp/x509up_u500 -H "User-Agent: pilot/2017-04-04.001 (Python 2.6.6; Linux x86_64)" -H "Accept: application/json" "https://pandaserver.cern.ch:25443/server/panda/getJob?siteName=BNL-LSST&prodSourceLabel=mtest"

2017-04-20 17:17:45,751 | INFO     | MainThread | pilot.workflow.generic           | run                              | waiting for interrupts

2017-04-20 17:17:47,136 | WARNING  | Thread-6   | pilot.util.https                 | request                          | request failed (8960): curl: (35) timed out before SSL handshake

**Comment by complynx** [comment]
Right now it's merged into https://github.com/mlassnig/pilot2/tree/next, which for now is the main branch.

Have you selected right certificate, have you renovated it?

**Comment by pavlo-svirin** [comment]
Running the same command gives the same "not unsubscriptable" exception with the same proxy.

My cloned repo info:

$ git log

commit 4abb3ceccaadc20170c5d6220d6a21977afca563
Merge: 25e16cf 0cfcf57
Author: Paul Nilsson <paul.nilsson@cern.ch>
Date:   Thu Apr 6 18:16:44 2017 +0200
...
commit 2963f8cc31e4ce6c3717831f2bade97c51c7bd11
Merge: d64c5e7 f81831c
Author: Mario Lassnig <mario@lassnig.net>
Date:   Tue Mar 28 17:01:41 2017 +0200

    Merge pull request #8 from complynx/next

    Promises.
....

$ git status

[hellcat@gatoatlas pilot2]$ git status
# On branch next
nothing to commit (working directory clean)

$ voms-proxy-info
...
timeleft  : 11:37:43

**Comment by complynx** [comment]
Loot into mlassnig#15

**Comment by complynx** [comment]
2017-04-20 17:40:41,640 | DEBUG    | Thread-6   | pilot.util.https                 | request                          | request: curl -sS --compressed --connect-timeout 1 --max-time 3 --capath /etc/grid-security/certificates --cert /tmp/x509up_u89148 --cacert /tmp/x509up_u89148 --key /tmp/x509up_u89148 -H 'User-Agent: pilot/2017-04-04.001 (Python 2.6.6; Linux x86_64)' -H 'Accept: application/json' 'https://pandaserver.cern.ch:25443/server/panda/getJob?siteName=BNL-LSST&prodSourceLabel=mtest'
2017-04-20 17:40:41,650 | INFO     | MainThread | pilot.workflow.generic           | run                              | waiting for interrupts
2017-04-20 17:40:42,615 | WARNING  | Thread-6   | pilot.control.job                | retrieve                         | did not get a job -- sleep 1000s and repeat -- status: 20
2017-04-20 17:40:51,689 | DEBUG    | Thread-4   | pilot.control.lifetime           | control                          | maximum lifetime reached: 10
2017-04-20 17:40:51,689 | INFO     | Thread-4   | pilot.control.lifetime           | control                          | lifetime: 10 used, 10 maximum

**Comment by complynx** [comment]
Already in mlassnig/next.
Issue closed.

**Comment by pavlo-svirin** [comment]
thanks, working now
