### ISSUE TITLE
Create new error code

### ISSUE THREAD

**Issue by PalNilsson** [PanDAWMS/pilot2#83]
Create new error code for the following case (currently labelled as a general stage-out problem):

`2018-07-27 07:04:49,168 | INFO     | executing command: /usr/bin/env rucio -v upload --rse BNL-OSG2_DATADISK --scope panda --guid 0e77c88c-74a7-4343-980f-c6104e612307 --summary /home/condor/local/atlas/execute/dir_72469/condorg_nPS5EtLj/PanDA_Pilot2_76596_1532674961/PanDA_Pilot-4005751905/4c4aa220-1bb8-4fb9-871d-ede4ee3ba614_1.job.log.tgz
2018-07-27 07:05:10,328 | ERROR    | Traceback (most recent call last):
  File "/home/condor/local/atlas/execute/dir_72469/condorg_nPS5EtLj/pilot2/pilot/control/data.py", line 543, in _do_stageout
    client.transfer(xdata, activity, **kwargs)
  File "/home/condor/local/atlas/execute/dir_72469/condorg_nPS5EtLj/pilot2/pilot/api/data.py", line 318, in transfer
    raise PilotException('Failed to transfer files using copytools=%s, error=%s' % (copytools, errors))
PilotException: Error code: 1301, message: An unknown pilot exception has occurred
Details: Failed to transfer files using copytools=['rucio'], error=[PilotException("no error information passed (http status code: 503 ('service_unavailable', 'unavailable'))]",)]

2018-07-27 07:05:10,328 | INFO     | summary of transferred files:
2018-07-27 07:05:10,329 | INFO     |  -- lfn=4c4aa220-1bb8-4fb9-871d-ede4ee3ba614_1.job.log.tgz, status_code=1137, status=failed
`

https://aipanda115.cern.ch/media/filebrowser/0e77c88c-74a7-4343-980f-c6104e612307/panda/tarball_PandaJob_4005751905_BNL_PROD_CONTR_TEST-condor/pilotlog.txt

**Comment by PalNilsson** [comment]
Added error code 1316, RUCIOSERVICEUNAVAILABLE: "Rucio: Service unavailable", used by rucio copy tool.
